apiVersion: v1
kind: Service
metadata:
  name: envoy-als
  namespace: monitoring
spec:
  selector:
    app: envoy-als
  type: LoadBalancer
  ports:
    - name: grpc-als
      protocol: TCP
      appProtocol: grpc
      port: 8080
      targetPort: 8080
    - name: http-monitoring
      protocol: TCP
      port: 19001
      targetPort: 19001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-als
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-als
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "19001"
      labels:
        app: envoy-als
    spec:
      containers:
        - name: envoy-als
          image: ghcr.io/zirain/als:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 19001
      volumes:
        - name: envoy-als
          configMap:
            name: envoy-als
