apiVersion: v1
data:
  mesh: |-
    extensionProviders:
    - name: file-log
      envoyFileAccessLog:
        path: /dev/stdout
    - name: grpc-log
      envoyHttpAls:
        service: envoy-als-server.istio-system.svc.cluster.local
        port: 9811
    defaultProviders:
      accessLogging: 
      - file-log
      - grpc-log
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
